### ISSUE TITLE
That libc6 version 2.38 is required is not documented

### ISSUE THREAD

**Issue by johnblommers** [arenasys/Lineworks#3]
Because when I launch 

```
bash source/start.sh
Traceback (most recent call last):
  File "/home/johnb/Desktop/lineworks/source/main.py", line 388, in loaded
    self.done()
  File "/home/johnb/Desktop/lineworks/source/main.py", line 392, in done
    start(self.engine, self.app, self._mode)
  File "/home/johnb/Desktop/lineworks/source/main.py", line 498, in start
    import gui
  File "/home/johnb/Desktop/lineworks/source/gui.py", line 20, in <module>
    import tabs
  File "/home/johnb/Desktop/lineworks/source/tabs.py", line 8, in <module>
    import spellcheck
  File "/home/johnb/Desktop/lineworks/source/spellcheck.py", line 1, in <module>
    import hunspell
  File "/home/johnb/Desktop/lineworks/venv/lib/python3.10/site-packages/hunspell/__init__.py", line 4, in <module>
    from .hunspell import HunspellWrap as Hunspell, HunspellFilePathError  # noqa: F401
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /home/johnb/Desktop/lineworks/venv/lib/python3.10/site-packages/hunspell/libhunspell-1.7.so.0)

TRACEBACK SAVED: crash.log
````

I'm running PopOS 22.04 which has libc6 version 2.35.

**Comment by arenasys** [comment]
Need to build `cython_hunspell` from source, and probably `cdifflib` also (also prebuilt against libc 2.38):
```
source venv/bin/activate
pip uninstall -y cyhunspell cdifflib
pip install cdifflib==1.2.6
export CPLUS_INCLUDE_PATH="$PWD/python/include/python3.10"
pip install https://github.com/MSeal/cython_hunspell/archive/refs/tags/2.0.3.tar.gz
```
For developers, with the venv active you can skip the `start.sh` and `launch.py` wrapper, and run with `python source/main.py` directly.
